image: node:16.17.1

pipelines:
  pull-requests:
    '**':
      - step:
          name: Build and test
          script:
            - npm --version
            - node --version
            - npm ci
            - npm run test:unit
  branches:
    master:
      - parallel:
          - step:
              name: Build and Test
              script:
                - npm ci
                - npm run test:unit
                - npm run build
          - step:
              name: Security Scan
              script:
                # Run a security scan for sensitive data.
                # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
                - pipe: atlassian/git-secrets-scan:0.5.1
      - step:
          name: Build and Push Docker Image to Docker HUB
          services:
            - docker
          script:
            - export IMAGE_NAME="${DOCKER_HUB_USER}/${BITBUCKET_REPO_SLUG}:latest"
            - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
            - docker build -t "$IMAGE_NAME" . --build-arg env='prod'
            - docker push "$IMAGE_NAME"
      - step:
          name: Deploy to AWS PROD
          script:
            - pipe: atlassian/ssh-run:0.4.1
              variables:
                SSH_USER: $SSH_USER_PROD
                SERVER: $SERVER_IP_PROD
                MODE: 'command'
                COMMAND: './deploy-to-prod.sh'
    dev:
      - parallel:
          - step:
              name: Build and Test
              caches:
                - node
              script:
                - npm ci
                - npm run test:unit
                - npm run build
          - step:
              name: Security Scan
              script:
                # Run a security scan for sensitive data.
                # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
                - pipe: atlassian/git-secrets-scan:0.5.1
      - step:
          name: Build and Push Docker Image to Docker HUB
          services:
            - docker
          script:
            - export IMAGE_NAME="${DOCKER_HUB_USER}/dev_${BITBUCKET_REPO_SLUG}:latest"
            - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
            - docker build -t "$IMAGE_NAME" . --build-arg env='dev'
            - docker push "$IMAGE_NAME"
      - step:
          name: Deploy to AWS DEV
          script:
            - pipe: atlassian/ssh-run:0.4.1
              variables:
                SSH_USER: $SSH_USER_DEV
                SERVER: $SERVER_IP_DEV
                MODE: 'command'
                COMMAND: './deploy-to-dev.sh'