# THIS DOCKER COMPOSE FOR LOCAL USAGE

version: "3.7" #have to use it unless you upgrade docker-compose
services:
    hotel_backend:
        container_name: hotel_backend
        build:
            context: .
            dockerfile: Dockerfile
        # If you want change port, then please change only first port,
        # and also don't forget to change port in frontend app
        ports:
            - "8080:8080"
        depends_on:
            - hotel_db
    hotel_db:
        image: postgres:14.1
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5455:5432"
    # MailDev is for local test email receiving
    mail_dev:
        image: maildev/maildev
        ports:
            - "1080:1080" # use this to mail UI - http://localhost:1080
            - "1025:1025"

